# Site settings
title: NECX
email: katyhuff@gmail.com
description: "Website for the Strategic Instructional Innovations Program Project: Collaborative Open-Source Curiculum Development"
baseurl: "/necx" # the subpath of your site, e.g. /blog
url: "https://arfc.github.io/necx" # the base hostname & protocol for your site
twitter_username: katyhuff
github_username: arfc
logo: "/img/nekx.png"
collections:
  nodes:
    output: true
    permalink: /:collection/:path


defaults:
  -
    scope:
      path: "_nodes/"
      type: nodes  # <= here I specify the nodes collection
    values:
      layout: nodes
      exclude: ['_nodes/*/assessments/*.md','_nodes/*/exercises/*.md','_nodes/nodes.md']

# Agency color settings
color:
  primary: e87722
  primary-dark: d45d00
  secondary: 606eb2
  secondary-dark: 002058
  transparent: rgba(0,21,56,0.7)

# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

# Jekyll Scholar
scholar:
  style: chicago-author-date
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibliography

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  
  repository: papers
